// <auto-generated />
using ConsoleAppDevart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleAppDevart.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20250422180313_Iniziale")]
    partial class Iniziale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ConsoleAppDevart.Models.Grupo", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("NAME");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar2(300)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("STATUS");

                    b.HasKey("Name");

                    b.ToTable("TB_TST_GRUPO", "DOTNET");
                });

            modelBuilder.Entity("ConsoleAppDevart.Models.Person", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("NAME");

                    b.Property<string>("GrupoName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar2(30)")
                        .HasColumnName("GRUPONAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("STATUS");

                    b.HasKey("Name");

                    b.ToTable("TB_TST_PEOPLE", "DOTNET");
                });

            modelBuilder.Entity("ConsoleAppDevart.Models.Person", b =>
                {
                    b.HasOne("ConsoleAppDevart.Models.Grupo", "Grupo")
                        .WithMany("Persons")
                        .HasForeignKey("Name");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ConsoleAppDevart.Models.Grupo", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
