// <auto-generated />
using ConsoleAppDevart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleAppDevart.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ConsoleAppDevart.Models.Grupo", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("NAME");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar2(300)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("STATUS");

                    b.HasKey("Name");

                    b.ToTable("TB_TST_GRUPO", "DOTNET");

                    b.HasData(
                        new
                        {
                            Name = "Grupo1",
                            Description = "Descrizione Grupo1",
                            Status = "A"
                        },
                        new
                        {
                            Name = "Grupo2",
                            Description = "Descrizione Grupo2",
                            Status = "A"
                        },
                        new
                        {
                            Name = "Grupo3",
                            Description = "Descrizione Grupo3",
                            Status = "A"
                        },
                        new
                        {
                            Name = "Grupo4",
                            Description = "Descrizione Grupo4",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("ConsoleAppDevart.Models.Person", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("NAME");

                    b.Property<string>("GrupoName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar2(30)")
                        .HasColumnName("GRUPONAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2")
                        .HasColumnName("STATUS");

                    b.HasKey("Name");

                    b.HasIndex("GrupoName");

                    b.ToTable("TB_TST_PEOPLE", "DOTNET");

                    b.HasData(
                        new
                        {
                            Name = "User1-1",
                            GrupoName = "Grupo1",
                            Status = "A"
                        },
                        new
                        {
                            Name = "User2-1",
                            GrupoName = "Grupo1",
                            Status = "A"
                        },
                        new
                        {
                            Name = "User3-1",
                            GrupoName = "Grupo1",
                            Status = "I"
                        },
                        new
                        {
                            Name = "User4-1",
                            GrupoName = "Grupo1",
                            Status = "A"
                        },
                        new
                        {
                            Name = "User5-2",
                            GrupoName = "Grupo2",
                            Status = "A"
                        },
                        new
                        {
                            Name = "User6-2",
                            GrupoName = "Grupo2",
                            Status = "A"
                        },
                        new
                        {
                            Name = "User7-2",
                            GrupoName = "Grupo2",
                            Status = "I"
                        },
                        new
                        {
                            Name = "User8-1",
                            GrupoName = "Grupo1",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("ConsoleAppDevart.Models.Person", b =>
                {
                    b.HasOne("ConsoleAppDevart.Models.Grupo", "Grupo")
                        .WithMany("Persons")
                        .HasForeignKey("GrupoName");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ConsoleAppDevart.Models.Grupo", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
